api_key: 'key-cb78195c9fe570d7aede6c2a50fb2763'
domain: 'smtp.mailgun.org'
username: 'postmaster@sandbox4ea8eba4cefb460db058755433978bcd.mailgun.org'
password: '5e08118ec55cb1a5d24babe40f0ea202'
mailgun_username: 'jannikwortmann92@gmail.com'
mailgun_password: 'Pilsbier123'